### ISSUE TITLE
Accept PR, create crate

### ISSUE THREAD

**Issue by bestouff** [moosingin3space/pktparse-rs#5]
Hi,

I'd like to have this available in crates.io; could you accept (or reject) pull requests from @ekse and I and make a proper release ? Otherwise would you allow one of us to do it ?

Regards,
        Xav

**Comment by moosingin3space** [comment]
Hey,

I don't have a crates.io name for this project, you may go ahead and claim it! My work has moved me in a different direction, so that's why I haven't been as responsive with accepting PRs.

Thanks,
Nathan

**Comment by bestouff** [comment]
OK right I understand. Do you have a preferred licence (e.g. MIT or LGPLv3) ?

**Comment by moosingin3space** [comment]
I do not have a preferred license.

**Comment by bestouff** [comment]
OK, I'll do an LGPLv3 release as soon as I have an answer from @ekse (I retrieved its PR into my repo). Thanks !

**Comment by ekse** [comment]
Thanks @bestouff Lgpl is fine by me too.

**Comment by Stargateur** [comment]
LGPLv3 is very restrictive, could you consider the classic "Apache-2.0 OR MIT" dual licences ? The actual licences would disallow me to use this crates at work (can't make code open source and I don't see the point to put this on an utils crates specially because nom is MIT).

**Comment by bestouff** [comment]
I think you have mistaken LGPLv3 for GPLv3. LGPL doesn't require you to do anything with your sourcecode at all, you can keep it proprietary as you wish. You just have to publish changes you'd make to `pktparse-rs` back.

**Comment by Stargateur** [comment]
@bestouff Oh, thanks, I miss understand "If you distribute this library in an executable, you must make the source available for 3 years." from https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)#summary.

Well, That perfect, nevermind.

**Comment by bestouff** [comment]
No problem; enjoy !
